enableLoggingRequestDetails: false
server:
  error:
    include-message: always
    include-binding-errors: always
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  pattern:
    dateformat: HH:mm:ss
spring:
  main:
    banner-mode: off
  datasource:
    password: admin
    url: jdbc:mysql://localhost:3306/gym?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  mail:
    username: marcoslopezdev18@gmail.com
  jwt:
    secret: yGhqRjT4eibeqKq25Ps5DM2pWUdkVhPS
