#Desactivo los detalles de la request
enableLoggingRequestDetails: false
server:
  error:
    #Al haber un error envia siempre message y los parametros
    include-message: always
    include-binding-errors: always
#Se asigna los niveles de Logging para mensajes en consola
logging:
  level:
    root: INFO
    web: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
  #Cambio el formato de la hora en consola
  pattern:
    dateformat: HH:mm:ss
spring:
  main:
    #Desactivo el Banner de Spring Booy de consola
    banner-mode: off
  datasource:
    password: naruto30
    url: jdbc:mysql://localhost:3306/gym?useSSL=true&useTimezone=true&serverTimezone=UTC
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #Activa el mostrar el SQL ejecutado
    show-sql: true
    #Revoco el manejo de la Transaccion a JPA (Recomendable)
    open-in-view: false
    properties:
      hibernate:
        #Dialecto que usa Hibernate para las querys
        dialect: org.hibernate.dialect.MySQL8Dialect
        #Muestra el SQL ejecutado en consola en Columna
        format_sql: true
  mail:
    username: marcoslopezdev18@gmail.com
  jwt:
    secret: yGhqRjT4eibeqKq25Ps5DM2pWUdkVhPS
